import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

bool isNumeric( String s ) {
  if ( s.isEmpty ) return false;
  final n = num.tryParse(s);
  return ( n == null ) ? false : true;
}

void mostrarAlerta(BuildContext context, String mensaje ) {
  showDialog(
    context: context,
    builder: ( context ) {
      return AlertDialog(
        title: Text('Error'),
        content: Text(mensaje),
        actions: <Widget>[
          FlatButton(
            child: Text('Ok'),
            onPressed: ()=> Navigator.of(context).pop(),
          )
        ],
      );
    }
  );
}

void mostrarAvisoLegal(BuildContext context) {
  showAboutDialog(
    context: context,
    applicationIcon: Image(image: AssetImage('assets/img/propio/rostro.png'),width: 50,height: 50,),
    applicationName: 'Artensanos a la Mano',
    applicationVersion: '1.0',
    useRootNavigator: false,
    children: <Widget>[
      Image(image: AssetImage('assets/img/propio/Letras.png')),
    ],
    applicationLegalese: 'AVISO LEGAL\n'+
    'En este espacio, el usuario, podrá encontrar toda la información relativa a los términos y condiciones legales que definen las relaciones entre los usuarios y nosotros como responsables de esta aplicación móvil. Como usuario, es importante que conozcas estos términos antes de continuar tu navegación. ValorArte Mexico. Como responsable de esta aplicación móvil, asume el compromiso de procesar la información de nuestros usuarios y clientes con plenas garantías y cumplir con los requisitos nacionales y europeos que regulan la recopilación y uso de los datos personales de nuestros usuarios. Esta aplicación móvil, por tanto, cumple rigurosamente con el RGPD (REGLAMENTO (UE) 2016/679 de protección de datos) y la LSSI-CE la Ley 34/2002, de 11 de julio, de servicios de la sociedad de la información y de comercio electrónico.'
    +'\n\nCOMPROMISOS Y OBLIGACIONES DE LOS USUARIOS\n'
    +'El Usuario queda informado, y se compromete a utilizar la aplicación móvil, sus servicios y contenidos sin contravenir la legislación vigente, la buena fe y el orden público.'
    +'\nQueda prohibido el uso de la aplicación móvil, con fines ilícitos o lesivos, o que, de cualquier forma, puedan causar perjuicio o impedir el normal funcionamiento de la aplicación móvil. Respecto de los contenidos de esta aplicación móvil, se prohíbe: Su reproducción, distribución o modificación, total o parcial, a menos que se cuente con la autorización de sus legítimos titulares; cualquier vulneración de los derechos del prestador o de los legítimos titulares.'
    +'\nEn la utilización de la aplicación móvil, el Usuario se compromete a no llevar a cabo ninguna conducta que pudiera dañar la imagen, los intereses y los derechos de o de terceros o que pudiera dañar, inutilizar o sobrecargar el portal, lo que impidiera, de cualquier forma, la normal utilización de la aplicación móvil. No obstante, debe ser consciente de que las medidas de seguridad de los sistemas informáticos en Internet no son enteramente fiables y que, por tanto el Titular no puede garantizar la inexistencia de virus u otros elementos que puedan producir alteraciones en los sistemas informáticos (software y hardware) del Usuario o en sus documentos electrónicos y ficheros contenidos en los mismos aunque el Titular pone todos los medios necesarios y toma las medidas de seguridad oportunas para evitar la presencia de estos elementos dañinos.'
    +'\nLos datos personales que facilite al Titular pueden ser almacenados en bases de datos automatizadas o no, cuya titularidad corresponde en exclusiva a el Titular, que asume todas las medidas de índole técnica, organizativa y de seguridad que garantizan la confidencialidad, integridad y calidad de la información contenida en las mismas de acuerdo con lo establecido en la normativa vigente en protección de datos.'

    +'\n\nRECLAMACIONES\n'
    +'Se informa que existen hojas de reclamación a disposición de usuarios y clientes. El Usuario podrá realizar reclamaciones solicitando su hoja de reclamación o remitiendo un correo electrónico a valorartemexicoo@gmail.com indicando su nombre y apellidos, el servicio y/o producto adquirido y exponiendo los motivos de su reclamación.'
    +'\nEl usuario/comprador podrá notificarnos la reclamación, bien a través de correo electrónico a: valorartemexicoo@gmail.com, si lo desea adjuntando el siguiente formulario de reclamación: El servicio/producto:'
    +'\nAdquirido el día:\n'
    +'Nombre del usuario:\n'
    +'Domicilio del usuario:\n'
    +'Firma del usuario (solo si se presenta en papel):\n'
    +'Fecha: Motivo de la reclamación:\n'

    +'\n\nLEY APLICABLE Y JURISDICCIÓN\n'
    +'Con carácter general las relaciones entre con los Usuarios de sus servicios telemáticos, presentes en esta aplicación móvil se encuentran sometidas a la legislación y jurisdicción mexicanas y a los tribunales.'

    +'\n\nCONTACTO\n'
    +'En caso de que cualquier Usuario tuviese alguna duda acerca de estas Condiciones legales o cualquier comentario sobre la aplicación móvil, por favor diríjase a valorartemexicoo@gmail.com.'
    +'\nDe parte del equipo que formamos ValorArte Mexico, te agradecemos el tiempo dedicado en leer este Aviso Legal. Esperamos que tengas una buena experiencia.'
  );
}

void mostrarPoliticaPrivacidad(BuildContext context){
  showDialog(
    context: context,
    builder: ( context ) {
      return AlertDialog(
        title: Text('Política de Privacidad'),
        content: Text(
          'ValorArte México, es la empresa responsable del tratamiento de los datos personales que nos proporcione, los cuales serán protegidos conforme a lo dispuesto por la Ley de Protección de Datos Personales en Posesión de Sujetos Obligados para el Estado de Puebla, y demás normatividad que resulte aplicable.'
          +'\nFinalidades del tratamiento'
          +'\nSus datos personales, serán utilizados para las siguientes finalidades:'
          +'\na) recuperar la contraseña en caso de perderla'
          +'\nb) fines estadísticos'
          +'\nc) acuerdos en la comunicación',
        style: TextStyle(
          color: Colors.black54,
          fontSize: 12
        ),
        ),
        actions: <Widget>[
          Column(
            children: <Widget>[
              Image(image: AssetImage('assets/img/propio/Letras.png')),
              Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: <Widget>[
                  FlatButton(
                    child: Text('Privacy policies'),
                    onPressed: (){
                      Navigator.of(context).pushNamed('PoliticasPages');
                    } 
                  ),
                  FlatButton(
                    child: Text('Close'),
                    onPressed: ()=> Navigator.of(context).pop(),
                  )
                ],
              ),
            ],
          ),
        ],
      );
    }
  );
}

void mostrarCarga(BuildContext context) {
  showCupertinoDialog(
    context: context,
    builder: ( context ) {
      return AlertDialog(
        elevation: 10,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(300)
        ),
        title: Center(child: Column(
          children: <Widget>[
            Text('Cargando'),
            SizedBox(height: 10,),
            CircularProgressIndicator()
          ],
        )),
      );
    }
  );
}


List<String> municipiosLista (){ 
    List<String> municipios=[
      "Acajete",
      "Acateno",
      "Acatlán",
      "Acatzingo de Hidalgo",
      "Acteopan",
      "Ahuacatlán",
      "Ahuatlán",
      "Ahuazotepec",
      "Ahuehuetitla",
      "Ajalpan",
      "Albino Zertuche",
      "Aljojuca",
      "Altepexi",
      "Amixtlán",
      "Amozoc",
      "Aquixtla",
      "Atempan",
      "Atexcal",
      "Atlixco",
      "Atoyatempan",
      "Atzala",
      "Atzitzihuacán",
      "Atzitzintla",
      "Axutla",
      "Ayotoxco de Guerrero",
      "Calpan",
      "Caltepec",
      "Camocuautla",
      "Caxhuacan",
      "Coatepec",
      "Coatzingo",
      "Cohetzala",
      "Cohuecan",
      "Coronango",
      "Coxcatlán",
      "Coyomeapan",
      "Coyotepec",
      "Cuapiaxtla de Madero",
      "Cuautempan",
      "Cuautinchán",
      "Cuautlancingo",
      "Cuayuca de Andrade",
      "Cuetzalan del Progreso",
      "Cuyoaco",
      "Chalchicomula de Sesma",
      "Chapulco",
      "Chiautla",
      "Chiautzingo",
      "Chiconcuautla",
      "Chichiquila",
      "Chietla",
      "Chigmecatitlán",
      "Chignahuapan",
      "Chignautla",
      "Chila",
      "Chila de la Sal",
      "Honey",
      "Chilchotla",
      "Chinantla",
      "Domingo Arenas",
      "Eloxochitlán",
      "Epatlán",
      "Esperanza",
      "Francisco Z. Mena",
      "General Felipe Ángeles",
      "Guadalupe",
      "Guadalupe Victoria",
      "Hermenegildo Galeana",
      "Huaquechula",
      "Huatlatlauca",
      "Huauchinango",
      "Huehuetla",
      "Huehuetlán el Chico",
      "Huejotzingo",
      "Hueyapan",
      "Hueytamalco",
      "Hueytlalpan",
      "Huitzilan de Serdán",
      "Huitziltepec",
      "Atlequizayan",
      "Ixcamilpa de Guerrero",
      "Ixcaquixtla",
      "Ixtacamaxtitlán",
      "Ixtepec",
      "Izúcar de Matamoros",
      "Jalpan",
      "Jolalpan",
      "Jonotla",
      "Jopala",
      "Juan C. Bonilla",
      "Juan Galindo",
      "Juan N. Méndez",
      "Lafragua",
      "Libres",
      "La Magdalena Tlatlauquitepec",
      "Mazapiltepec de Juárez",
      "Mixtla",
      "Molcaxac",
      "Cañada Morelos",
      "Naupan",
      "Nauzontla",
      "Nealtican",
      "Nicolás Bravo",
      "Nopalucan",
      "Ocotepec",
      "Ocoyucan",
      "Olintla",
      "Oriental",
      "Pahuatlán",
      "Palmar de Bravo",
      "Pantepec",
      "Petlalcingo",
      "Piaxtla",
      "Puebla",
      "Quecholac",
      "Quimixtlán",
      "Rafael Lara Grajales",
      "Los Reyes de Juárez",
      "San Andrés Cholula",
      "San Antonio Cañada",
      "San Diego La Mesa Tochimiltzingo",
      "San Felipe Teotlalcingo",
      "San Felipe Tepatlán",
      "San Gabriel Chilac",
      "San Gregorio Atzompa",
      "San Jerónimo Tecuanipan",
      "San Jerónimo Xayacatlán",
      "San José Chiapa",
      "San José Miahuatlán",
      "San Juan Atenco",
      "San Juan Atzompa",
      "San Martín Texmelucan",
      "San Martín Totoltepec",
      "San Matías Tlalancaleca",
      "San Miguel Ixitlán",
      "San Miguel Xoxtla",
      "San Nicolás Buenos Aires",
      "San Nicolás de los Ranchos",
      "San Pablo Anicano",
      "San Pedro Cholula",
      "San Pedro Yeloixtlahuaca",
      "San Salvador el Seco",
      "San Salvador el Verde",
      "San Salvador Huixcolotla",
      "San Sebastián Tlacotepec",
      "Santa Catarina Tlaltempan",
      "Santa Inés Ahuatempan",
      "Santa Isabel Cholula",
      "Santiago Miahuatlán",
      "Huehuetlán el Grande",
      "Santo Tomás Hueyotlipan",
      "Soltepec",
      "Tecali de Herrera",
      "Tecamachalco",
      "Tecomatlán",
      "Tehuacán",
      "Tehuitzingo",
      "Tenampulco",
      "Teopantlán",
      "Teotlalco",
      "Tepanco de López",
      "Tepango de Rodríguez",
      "Tepatlaxco de Hidalgo",
      "Tepeaca",
      "Tepemaxalco",
      "Tepeojuma",
      "Tepetzintla",
      "Tepexco",
      "Tepexi de Rodríguez",
      "Tepeyahualco",
      "Tepeyahualco de Cuauhtémoc",
      "Tetela de Ocampo",
      "Teteles de Ávila Castillo",
      "Teziutlán",
      "Tianguismanalco",
      "Tilapa",
      "Tlacotepec de Benito Juárez",
      "Tlacuilotepec",
      "Tlachichuca",
      "Tlahuapan",
      "Tlaltenango",
      "Tlanepantla",
      "Tlaola",
      "Tlapacoya",
      "Tlapanalá",
      "Tlatlauquitepec",
      "Tlaxco",
      "Tochimilco",
      "Tochtepec",
      "Totoltepec de Guerrero",
      "Tulcingo",
      "Tuzamapan de Galeana",
      "Tzicatlacoyan",
      "Venustiano Carranza",
      "Vicente Guerrero",
      "Xayacatlán de Bravo",
      "Xicotepec",
      "Xicotlán",
      "Xiutetelco",
      "Xochiapulco",
      "Xochiltepec",
      "Xochitlán de Vicente Suárez",
      "Xochitlán Todos Santos",
      "Yaonáhuac",
      "Yehualtepec",
      "Zacapala",
      "Zacapoaxtla",
      "Zacatlán",
      "Zapotitlán",
      "Zapotitlán de Méndez",
      "Zaragoza",
      "Zautla",
      "Zihuateutla",
      "Zinacatepec",
      "Zongozotla",
      "Zoquiapan",
      "Zoquitlán",
    ];
  return municipios;
}

List<String> municipiosRegionLista (){ 
    List<String> regiones=[
      "4",
      "2",
      "6",
      "3",
      "5",
      "1",
      "5",
      "1",
      "6",
      "7",
      "6",
      "3",
      "7",
      "1",
      "4",
      "1",
      "2",
      "6",
      "5",
      "4",
      "5",
      "5",
      "3",
      "6",
      "2",
      "4",
      "7",
      "1",
      "2",
      "1",
      "6",
      "6",
      "5",
      "4",
      "7",
      "7",
      "6",
      "3",
      "1",
      "4",
      "4",
      "6",
      "2",
      "3",
      "3",
      "7",
      "6",
      "4",
      "1",
      "3",
      "5",
      "6",
      "1",
      "2",
      "6",
      "6",
      "1",
      "3",
      "6",
      "4",
      "7",
      "5",
      "3",
      "1",
      "3",
      "6",
      "3",
      "1",
      "5",
      "6",
      "1",
      "2",
      "6",
      "4",
      "2",
      "2",
      "2",
      "2",
      "6",
      "2",
      "6",
      "6",
      "1",
      "2",
      "5",
      "1",
      "6",
      "2",
      "1",
      "4",
      "1",
      "6",
      "3",
      "3",
      "6",
      "3",
      "4",
      "6",
      "3",
      "1",
      "2",
      "4",
      "7",
      "4",
      "3",
      "4",
      "1",
      "3",
      "1",
      "3",
      "1",
      "6",
      "6",
      "4",
      "3",
      "3",
      "3",
      "3",
      "4",
      "7",
      "5",
      "4",
      "1",
      "7",
      "5",
      "5",
      "6",
      "3",
      "7",
      "3",
      "6",
      "4",
      "5",
      "4",
      "6",
      "4",
      "3",
      "4",
      "6",
      "4",
      "6",
      "3",
      "4",
      "3",
      "7",
      "6",
      "6",
      "5",
      "7",
      "6",
      "4",
      "3",
      "4",
      "3",
      "6",
      "7",
      "6",
      "2",
      "5",
      "6",
      "7",
      "1",
      "4",
      "4",
      "5",
      "5",
      "1",
      "5",
      "6",
      "3",
      "4",
      "1",
      "2",
      "2",
      "5",
      "5",
      "7",
      "1",
      "3",
      "4",
      "4",
      "4",
      "1",
      "1",
      "5",
      "2",
      "1",
      "5",
      "4",
      "6",
      "6",
      "2",
      "6",
      "1",
      "7",
      "6",
      "1",
      "6",
      "2",
      "1",
      "5",
      "2",
      "6",
      "2",
      "7",
      "6",
      "2",
      "1",
      "7",
      "2",
      "2",
      "2",
      "1",
      "7",
      "1",
      "2",
      "7",
    ];
  return regiones;
}